apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-job
  namespace: question-system
spec:
  template:
    spec:
      serviceAccountName: kafka-job-sa
      containers:
      - name: kafka-topic-creator
        image: bitnami/kafka:3.6
        command:
        - /bin/bash
        - -c
        - |
          echo "Waiting for Kafka..."
          sleep 30
          kafka-topics.sh --create \
            --bootstrap-server kafka-kraft:9092 \
            --replication-factor 1 \
            --partitions 3 \
            --topic questions \
            --if-not-exists
          echo "Topic created"
          kafka-topics.sh --list --bootstrap-server kafka-kraft:9092
      restartPolicy: Never
  backoffLimit: 4
