# KROK 6 (mTLS): certyfikaty klienta dla usług wewnętrznych.
# UWAGA: dla Vault issuer przez endpoint pki/issue/* cert-manager wymaga
# certificateRequestPolicy=SignVerbatim (zachowanie klucza publicznego z CSR).
# Bez tego: "public key does not match the CSR" (InvalidCertificate).
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fastapi-mtls
  namespace: davtro02
spec:
  secretName: fastapi-mtls
  duration: 720h   # 30d
  renewBefore: 168h # 7d
  commonName: fastapi-web-app.davtro02.svc
  dnsNames:
    - fastapi-web-app.davtro02.svc
    - fastapi-web-app.davtro02.svc.cluster.local
    - fastapi-web-app-svc.davtro02.svc
    - fastapi-web-app-svc.davtro02.svc.cluster.local
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  issuerRef:
    name: vault-issuer-internal
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - digital signature
    - key encipherment
    - client auth
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: message-processor-mtls
  namespace: davtro02
spec:
  secretName: message-processor-mtls
  duration: 720h
  renewBefore: 168h
  commonName: message-processor.davtro02.svc
  dnsNames:
    - message-processor.davtro02.svc
    - message-processor.davtro02.svc.cluster.local
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  issuerRef:
    name: vault-issuer-internal
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - digital signature
    - key encipherment
    - client auth
    - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spring-app-mtls
  namespace: davtro02
spec:
  secretName: spring-app-mtls
  duration: 720h
  renewBefore: 168h
  commonName: spring-app.davtro02.svc
  dnsNames:
    - spring-app.davtro02.svc
    - spring-app.davtro02.svc.cluster.local
    - spring-app-svc.davtro02.svc
    - spring-app-svc.davtro02.svc.cluster.local
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  issuerRef:
    name: vault-issuer-internal
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - digital signature
    - key encipherment
    - client auth
    - server auth
