apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-job-sa
  namespace: question-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: question-system-sa
  namespace: question-system
