server.port=8081
spring.datasource.url=jdbc:postgresql://postgres-clusterip:5432/davtro
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.kafka.bootstrap-servers=kafka-kraft:9092
management.endpoints.web.exposure.include=health,prometheus
