# UWAGA: Placeholder - w produkcji uzyj Vault (ArgoCD Vault Plugin)
apiVersion: v1
kind: Secret
metadata:
  name: davtro-secrets
  namespace: davtro
type: Opaque
stringData:
  DB_USER: "<path:secret/data/davtro#db_user>"
  DB_PASSWORD: "<path:secret/data/davtro#db_password>"
  SMTP_USER: "<path:secret/data/davtro#smtp_user>"
  SMTP_PASSWORD: "<path:secret/data/davtro#smtp_password>"
