# UWAGA: W produkcji uzyj ArgoCD Vault Plugin, SealedSecrets lub ExternalSecrets
apiVersion: v1
kind: Secret
metadata:
  name: davtro-secrets
  namespace: davtro
type: Opaque
stringData:
  DB_USER: "davtro"
  DB_PASSWORD: "changeme"
  SMTP_USER: ""
  SMTP_PASSWORD: ""
  VAULT_ROOT_TOKEN: "root"
